### ISSUE TITLE
Error after migrating python3

### ISSUE THREAD

**Issue by ssoto** [andalugeeks/andaluh-py#9]
Module user reported this issue:
```
Traceback (most recent call last):
  File "/home/soto/.virtualenvs/andaluh-py-py35/bin/andaluh", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/soto/src/andaluh-py/bin/andaluh", line 32
    print epa(args.text, vaf=vaf, vvf=vvf)
            ^
```

This error has introduced after migration to python3.

**Comment by ssoto** [comment]
I tried uninstalling package and reinstalling it and it from source and works again:
```
pip uninstall andaluh
cd andaluh-py/
pip install -e .
```
